## Izbor atributa

### Embedded metoda

In [ ]:
import pandas as pd

df = pd.read_csv("../data/processed/final.csv")
print(df.shape)
df.head()

(25562, 27)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,count_submitted_TMA,std_score_CMA,std_score_TMA,total_assessments_CMA,total_assessments_TMA,submission_rate_TMA,submission_rate_CMA,total_clicks,last_active_day,unique_activities
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,2.0,0.0,4.949747,0.0,2.0,1.0,0.0,587.0,87.0,6.0
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,2.0,0.0,1.414214,0.0,2.0,1.0,0.0,821.0,90.0,6.0
2,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,...,2.0,0.0,0.707107,0.0,2.0,1.0,0.0,992.0,90.0,7.0
3,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,...,2.0,0.0,27.577164,0.0,2.0,1.0,0.0,684.0,90.0,7.0
4,AAA,2013J,38053,M,Wales,A Level or Equivalent,80-90%,35-55,0,60,...,2.0,0.0,7.071068,0.0,2.0,1.0,0.0,1060.0,86.0,7.0

In [9]:
df['target']=df['final_result'].isin(["Fail","Withdrawn"]).astype(int)
df['target'].value_counts()

target
0    15385
1    10177
Name: count, dtype: int64

In [10]:
df['year']=df['code_presentation'].astype(str).str[:4]
df['year'].value_counts()

year
2014    14507
2013    11055
Name: count, dtype: int64

In [11]:
train_df=df[df['year']=="2013"].copy()
test_df=df[df['year']=="2014"].copy()
print(train_df.shape)
print(test_df.shape)

(11055, 29)
(14507, 29)

In [12]:
X_train=train_df.drop(columns=['final_result','target','id_student','year'], errors='ignore')
y_train=train_df['target']

X_test=test_df.drop(columns=['final_result','target','id_student','year'], errors='ignore')
y_test=test_df['target']

In [13]:
import joblib

pipeline=joblib.load("../models/final_model.pkl")
pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['num_of_prev_attempts', 'studied_credits',
       'avg_days_before_deadline_CMA', 'avg_days_before_deadline_TMA',
       'avg_score_CMA', 'avg_score_TMA', 'count_submitted_CMA',
       'count_submitted_TMA', 's...
       'submission_rate_CMA', 'total_clicks', 'last_active_day',
       'unique_activities'],
      dtype='str')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['code_module', 'code_presentation', 'gender', 'region',
       'highest_education', 'imd_band', 'age_band', 'disability'],
      dtype='str'))])),
                ('model', GradientBoostingClassifier(random_state=42))])

In [14]:
preprocessor=pipeline.named_steps['preprocessor']
model=pipeline.named_steps['model']

In [15]:
feature_names=preprocessor.get_feature_names_out()
feature_names

array(['num__num_of_prev_attempts', 'num__studied_credits',
       'num__avg_days_before_deadline_CMA',
       'num__avg_days_before_deadline_TMA', 'num__avg_score_CMA',
       'num__avg_score_TMA', 'num__count_submitted_CMA',
       'num__count_submitted_TMA', 'num__std_score_CMA',
       'num__std_score_TMA', 'num__total_assessments_CMA',
       'num__total_assessments_TMA', 'num__submission_rate_TMA',
       'num__submission_rate_CMA', 'num__total_clicks',
       'num__last_active_day', 'num__unique_activities',
       'cat__code_module_AAA', 'cat__code_module_BBB',
       'cat__code_module_DDD', 'cat__code_module_EEE',
       'cat__code_module_FFF', 'cat__code_module_GGG',
       'cat__code_presentation_2013B', 'cat__code_presentation_2013J',
       'cat__gender_F', 'cat__gender_M',
       'cat__region_East Anglian Region',
       'cat__region_East Midlands Region', 'cat__region_Ireland',
       'cat__region_London Region', 'cat__region_North Region',
       'cat__region_North Western Region', 'cat__region_Scotland',
       'cat__region_South East Region', 'cat__region_South Region',
       'cat__region_South West Region', 'cat__region_Wales',
       'cat__region_West Midlands Region', 'cat__region_Yorkshire Region',
       'cat__highest_education_A Level or Equivalent',
       'cat__highest_education_HE Qualification',
       'cat__highest_education_Lower Than A Level',
       'cat__highest_education_No Formal quals',
       'cat__highest_education_Post Graduate Qualification',
       'cat__imd_band_0-10%', 'cat__imd_band_10-20',
       'cat__imd_band_20-30%', 'cat__imd_band_30-40%',
       'cat__imd_band_40-50%', 'cat__imd_band_50-60%',
       'cat__imd_band_60-70%', 'cat__imd_band_70-80%',
       'cat__imd_band_80-90%', 'cat__imd_band_90-100%',
       'cat__imd_band_Unknown', 'cat__age_band_0-35',
       'cat__age_band_35-55', 'cat__age_band_55<=', 'cat__disability_N',
       'cat__disability_Y'], dtype=object)

In [16]:
feature_importance=pd.DataFrame({
    "feature":feature_names,
    "importance":model.feature_importances_
}).sort_values("importance", ascending=False)
feature_importance.head(10)

                                      feature  importance
12                   num__submission_rate_TMA    0.484211
5                          num__avg_score_TMA    0.210847
15                       num__last_active_day    0.124979
3           num__avg_days_before_deadline_TMA    0.058706
9                          num__std_score_TMA    0.018157
4                          num__avg_score_CMA    0.012987
42  cat__highest_education_Lower Than A Level    0.010691
17                       cat__code_module_AAA    0.009799
19                       cat__code_module_DDD    0.009215
14                          num__total_clicks    0.008891

In [17]:
feature_importance['feature']=(
    feature_importance['feature']
    .str.replace("num__", "", regex=False)
    .str.replace("cat__", "", regex=False)
)
feature_importance.head(10)

                                 feature  importance
12                   submission_rate_TMA    0.484211
5                          avg_score_TMA    0.210847
15                       last_active_day    0.124979
3           avg_days_before_deadline_TMA    0.058706
9                          std_score_TMA    0.018157
4                          avg_score_CMA    0.012987
42  highest_education_Lower Than A Level    0.010691
17                       code_module_AAA    0.009799
19                       code_module_DDD    0.009215
14                          total_clicks    0.008891

### Filter metoda

In [18]:
X_train_t=preprocessor.transform(X_train)
X_test_t=preprocessor.transform(X_test)

In [19]:
from sklearn.feature_selection import SelectKBest, f_classif
selector=SelectKBest(score_func=f_classif, k=15)
selector.fit(X_train_t,y_train)

SelectKBest(k=15)

In [20]:
selectkbest_results = pd.DataFrame({
    "feature": feature_names,
    "score": selector.scores_
}).sort_values("score", ascending=False)
selectkbest_results.head(10)

                                      feature        score
12                   num__submission_rate_TMA  3424.309483
5                          num__avg_score_TMA  3207.726116
15                       num__last_active_day  2462.552397
7                    num__count_submitted_TMA  1637.028622
14                          num__total_clicks   756.975207
16                     num__unique_activities   635.915214
11                 num__total_assessments_TMA   293.571591
42  cat__highest_education_Lower Than A Level   275.257692
0                   num__num_of_prev_attempts   203.283081
4                          num__avg_score_CMA   160.946592

In [21]:
selectkbest_results["feature"] = (
    selectkbest_results["feature"]
    .str.replace("num__", "", regex=False)
    .str.replace("cat__", "", regex=False)
)

selectkbest_results.head(10)

                                 feature        score
12                   submission_rate_TMA  3424.309483
5                          avg_score_TMA  3207.726116
15                       last_active_day  2462.552397
7                    count_submitted_TMA  1637.028622
14                          total_clicks   756.975207
16                     unique_activities   635.915214
11                 total_assessments_TMA   293.571591
42  highest_education_Lower Than A Level   275.257692
0                   num_of_prev_attempts   203.283081
4                          avg_score_CMA   160.946592

### Wrapper metoda

In [22]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

rfe_model=LogisticRegression(max_iter=1000)
rfe=RFE(estimator=rfe_model, n_features_to_select=10)
rfe.fit(X_train_t, y_train)

RFE(estimator=LogisticRegression(max_iter=1000), n_features_to_select=10)

In [23]:
rfe_rez = pd.DataFrame({
    "feature": feature_names,
    "selected": rfe.support_,
    "ranking": rfe.ranking_
}).sort_values("ranking")
rfe_rez.head(15)

                                         feature  selected  ranking
7                       num__count_submitted_TMA      True        1
5                             num__avg_score_TMA      True        1
12                      num__submission_rate_TMA      True        1
11                    num__total_assessments_TMA      True        1
15                          num__last_active_day      True        1
22                          cat__code_module_GGG      True        1
19                          cat__code_module_DDD      True        1
17                          cat__code_module_AAA      True        1
55                         cat__imd_band_Unknown      True        1
40  cat__highest_education_A Level or Equivalent      True        1
41       cat__highest_education_HE Qualification     False        2
45                           cat__imd_band_0-10%     False        3
4                             num__avg_score_CMA     False        4
10                    num__total_assessments_CMA     False        5
46                           cat__imd_band_10-20     False        6

In [24]:
selected = rfe_rez[rfe_rez["selected"] == True].copy()

selected["feature"] = (
    selected["feature"]
    .str.replace("num__", "", regex=False)
    .str.replace("cat__", "", regex=False)
)
selected

                                    feature  selected  ranking
7                       count_submitted_TMA      True        1
5                             avg_score_TMA      True        1
12                      submission_rate_TMA      True        1
11                    total_assessments_TMA      True        1
15                          last_active_day      True        1
22                          code_module_GGG      True        1
19                          code_module_DDD      True        1
17                          code_module_AAA      True        1
55                         imd_band_Unknown      True        1
40  highest_education_A Level or Equivalent      True        1